# Generated by Django 4.2.2 on 2023-06-13 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.IntegerField()),
                ('departure_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distance', models.CharField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_needed', models.IntegerField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_full', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_destination', to='journey.location')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='sample.jpg', null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('DE', 'Denied')], max_length=2)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_request', to='journey.demand')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='journey.offer')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.demand')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.offer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.requestboard')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_point',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='transport_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='stop_time',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='offer',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='journey.profile'),
        ),
        migrations.AddField(
            model_name='offer',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_origin', to='journey.location'),
        ),
        migrations.AddField(
            model_name='demand',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_destination', to='journey.location'),
        ),
        migrations.AddField(
            model_name='demand',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_origin', to='journey.location'),
        ),
        migrations.AddField(
            model_name='demand',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_passenger', to='journey.profile'),
        ),
        migrations.AddField(
            model_name='trip',
            name='offer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='journey.offer'),
            preserve_default=False,
        ),
    ]
